site_name: Fablabs.io developer guide
docs_dir: /mkdocs/docs
repo_url: https://github.com/fablabbcn/docs.fablabs.io
edit_uri: edit/master/mkdocs/docs/

pages: 
- Home: 'index.md'
- Examples: 'examples.md'
- Libraries: 'libraries.md'
theme:
    name: mkdocs
    custom_dir: /mkdocs/custom_theme
extra:
  links:
  - title: 'API Reference'
    url: 'http://docs.fablabs.io/swagger/index.html'
